export const NOP_ACTION = 'NOP_ACTION';

export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const CANCEL_AUTH_ACTION = 'CANCEL_AUTH_ACTION';
export const REQUEST_AUTH_ACTION = 'REQUEST_AUTH_ACTION';

export const TOKEN_REFRESH_BEGINS_ACTION = 'TOKEN_REFRESH_BEGINS_ACTION';
export const TOKEN_REFRESH_SUCCESS_ACTION = 'TOKEN_REFRESH_SUCCESS_ACTION';
export const TOKEN_REFRESH_FAILED_ACTION = 'TOKEN_REFRESH_FAILED_ACTION';

export const CANCEL_SIGNUP_ACTION = 'CANCEL_SIGNUP_ACTION';
export const REQUEST_SIGNUP_ACTION = 'REQUEST_SIGNUP_ACTION';

export const FETCH_USER_ACTION = 'FETCH_USER_ACTION';
