export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const CANCEL_AUTH_ACTION = 'CANCEL_AUTH_ACTION';
export const REQUEST_AUTH_ACTION = 'REQUEST_AUTH_ACTION';
export const REFRESH_TOKEN_ACTION = 'REFRESH_TOKEN_ACTION';
export const CANCEL_SIGNUP_ACTION = 'CANCEL_SIGNUP_ACTION';
export const REQUEST_SIGNUP_ACTION = 'REQUEST_SIGNUP_ACTION';

export const FETCH_USER_ACTION = 'FETCH_USER_ACTION';
