import {
  faUser,
  faEnvelope,
  faKey,
  faEye,
  faEyeSlash,
  faExclamationCircle,
  faTimes,
  faEllipsisV,
  faSearch,
  faBell,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChartBar,
  faArrowAltCircleRight,
  faArrowAltCircleLeft,
  faArrowAltCircleUp,
  faArrowAltCircleDown,
  faHeart,
  faBars,
  faSpinner,
} from '@fortawesome/free-solid-svg-icons';

const ICONS = {
  faUser,
  faEnvelope,
  faKey,
  faEye,
  faEyeSlash,
  faExclamationCircle,
  faTimes,
  faEllipsisV,
  faSearch,
  faBell,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChartBar,
  faArrowAltCircleRight,
  faArrowAltCircleLeft,
  faArrowAltCircleUp,
  faArrowAltCircleDown,
  faHeart,
  faBars,
  faSpinner,
};

export default ICONS;
