import {
  faUser,
  faEnvelope,
  faKey,
  faEye,
  faEyeSlash,
  faExclamationCircle,
  faTimes,
  faEllipsisV,
  faSearch,
  faBell,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChartBar,
  faArrowAltCircleRight,
  faArrowAltCircleLeft,
  faArrowAltCircleUp,
  faArrowAltCircleDown,
  faHeart,
  faBars,
  faSpinner,
} from '@fortawesome/free-solid-svg-icons';

import { faHeart as farHeart } from '@fortawesome/free-regular-svg-icons';

import {
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faGithub,
} from '@fortawesome/free-brands-svg-icons';

const ICONS = {
  faUser,
  faEnvelope,
  faKey,
  faEye,
  faEyeSlash,
  faExclamationCircle,
  faTimes,
  faEllipsisV,
  faSearch,
  faBell,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChartBar,
  faArrowAltCircleRight,
  faArrowAltCircleLeft,
  faArrowAltCircleUp,
  faArrowAltCircleDown,
  faHeart,
  farHeart,
  faBars,
  faSpinner,
  faInstagram,
  faFacebook,
  faTwitter,
  faLinkedin,
  faGithub,
};

export default ICONS;
